# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: '$(username)/demo'

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    goals: 'package -Dmaven.test.skip=true'
    publishJUnitResults: false

- task: DockerInstaller@0
  displayName: 'Install Docker 17.09.0-ce'

- script: |
    docker build -f Dockerfile -t $(imageName) .
    docker login --username=$(username) --password=$(password) registry.cn-hangzhou.aliyuncs.com
    docker push registry.cn-hangzhou.aliyuncs.com/haoyuv/project_test:$(imageName)
