spring:
  application:
    name: demo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysqldb:3306/security_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



#server:
#  ssl:
#    key-store: classpath:demo.key
#    key-store-password: 123456
#    key-password: 123456
